### ISSUE TITLE
`pb sync` gives "Error: Missing var value sync"

### ISSUE THREAD

**Issue by tkchia** [justinian/jsix#2]
Hello @justinian,

For some reason I am unable to build the project on my Ubuntu Focal system:
```
$ git clone https://github.com/justinian/jsix.git
$ cd jsix
...
$ sudo apt install python3-pip
...
$ pip3 install bonnibel
...
$ sudo apt install clang-10
...
$ pb sync
.../bonnibel/config.py:9: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated,
 as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  confdata = load(open(filename, "r"))
Generating build files for jsix 0.10.0-3daa07e...
Error: Missing var value sync
```

This is with the recent code commit https://github.com/justinian/jsix/commit/3daa07e31108703152b53ac08c1159fb5ffca6b7 for this repository.

Any clues on what I might be doing wrong?  Thank you!

**Comment by justinian** [comment]
Ah, my apologies, this is an error in my README - I had tried writing version 2 of `pb` in Rust, so you'll need to install it - either from the [releases in that project](https://github.com/justinian/bonnibel_rs/releases) or via `cargo` by [installing Rust and Cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html) and then using:

```cargo install bonnibel```

Honestly, this feels like it might be a little much for just a build tool, so I'll likely just go back to Python. It seems easier for people to do a `pip install` since Python is already installed everywhere. I just haven't actually finished reworking that yet.

**Comment by tkchia** [comment]
Hello @justinian,

> `cargo install bonnibel`

Thanks!  So I guess I should be looking at the [`bonnibel_rs`](https://github.com/justinian/bonnibel_rs) repository rather than [`bonnibel`](https://github.com/justinian/bonnibel).

I have now managed to get `pb sync` working.  There is just one minor issue I encountered --- I had to set the directory for temporary files (`$TMPDIR`) to somewhere in the same filesystem as my work directory, e.g.
```
$ TMPDIR="`pwd`" pb sync
```
Otherwise this happens:
```
$ pb sync
Downloading sysroot-llvm8-20190706.tar.bz2...
...
Error: failed to persist temporary file: Invalid cross-device link (os error 18)
```

> Honestly, this feels like it might be a little much for just a build tool, so I'll likely just go back to Python.

The choice is yours, I suppose. :-)

Thank you!
